name: fingerprint_auth_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  device_info_plus: ^9.0.3
  win32: ^5.0.0
  collection: ^1.18.0
  uuid: ^4.0.0
  shared_preferences: ^2.2.2
  flutter:
    sdk: flutter
  local_auth: ^2.1.8
  sqflite: ^2.3.0
  path: ^1.8.3
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.17.5
  firebase_database: ^10.5.7
  firebase_storage: ^11.6.5
  cloud_functions: ^4.6.5
  flutter_secure_storage: ^8.0.0
  pointycastle: ^3.7.3
  crypto: ^3.0.3
  mobile_scanner: ^3.5.5
  encrypt: ^5.0.1
  qr_flutter: ^4.1.0
  csv: ^5.0.0
  share_plus: ^7.0.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
