// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7-GohMxhXYzPjrMhLlTYdw0OzQAJSPIE',
    appId: '1:663176732768:web:102d322d5f299bdaaca305',
    messagingSenderId: '663176732768',
    projectId: 'project-22db4',
    authDomain: 'project-22db4.firebaseapp.com',
    storageBucket: 'project-22db4.firebasestorage.app',
    measurementId: 'G-JZHP9YN0SB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY54MpkNjY4-yCV2t5XBvej8snWKDAeFU',
    appId: '1:663176732768:android:d919341a28fdfe78aca305',
    messagingSenderId: '663176732768',
    projectId: 'project-22db4',
    storageBucket: 'project-22db4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFJK-U4AJNpWTlzEsXkVsbgf3N1e-EVb8',
    appId: '1:663176732768:ios:5d932f2315da36deaca305',
    messagingSenderId: '663176732768',
    projectId: 'project-22db4',
    storageBucket: 'project-22db4.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFJK-U4AJNpWTlzEsXkVsbgf3N1e-EVb8',
    appId: '1:663176732768:ios:5d932f2315da36deaca305',
    messagingSenderId: '663176732768',
    projectId: 'project-22db4',
    storageBucket: 'project-22db4.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7-GohMxhXYzPjrMhLlTYdw0OzQAJSPIE',
    appId: '1:663176732768:web:102d322d5f299bdaaca305',
    messagingSenderId: '663176732768',
    projectId: 'project-22db4',
    authDomain: 'project-22db4.firebaseapp.com',
    storageBucket: 'project-22db4.firebasestorage.app',
    measurementId: 'G-JZHP9YN0SB',
  );

}